### ISSUE TITLE
Strip disappears when an image is dragged onto the strip

### ISSUE THREAD

**Issue by dvdchr** [breach/mod_strip#32]
Please look at the screenshot below:
![mod_strip_image_bug](https://cloud.githubusercontent.com/assets/1299411/3561368/d306cb36-09bc-11e4-830f-85a8a0681b37.png)

**Explanation**
Notice that above the Google logo, there's a Wikipedia logo. It is actually a new frame / viewport, created on top of the existing `mod_strip`/tabs region because I dragged an image there. I can still switch tabs with the `ctrl + tab` key.

**Repro steps**
Drag an image to the `mod_strip` region.

**Expected behavior**
A new tab is created, containing the image source URL.

**Comment by spolu** [comment]
That's an interesting bug! :) So I guess the default behaviour of the webview is to open the image...
I wonder if we can disable that behaviour from the client code...

**Comment by t-lutz** [comment]
The submitted PR disables drop event alltogether. Dropping might be doing more clever things like loading the content in a new tab for example, but this PR is a bugfix, not a feature enhancement ;)

I think it might be a core problem: changing the content of a control panel should never be triggered in any way other than programatically.

**Comment by spolu** [comment]
This has been published in `v0.2.12`!
