### ISSUE TITLE
Moving tabs

### ISSUE THREAD

**Issue by EvanZ** [breach/mod_strip#34]
Would someone need to develop a module to rearrange tabs?

**Comment by Pectojin** [comment]
Currently the tabs are arranged in a stacking manner with the most recently opened/viewed tab first. Which means arranging the tabs doesn't really make sense. So I guess it would be more appropriate to develop a module to have the tabs not follow the stacking pattern.

**Comment by spolu** [comment]
Yes. That's the idea!
