### ISSUE TITLE
API rate limit  exceeded for...

### ISSUE THREAD

**Issue by HLFH** [breach/mod_strip#35]
Hi,

When I try to add mod_strip, I have the error

> API rate limit  exceeded for 92.xxx.xxx.xxx. (But here is the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

What could I do ?

Thanks in advance,

**Comment by spolu** [comment]
This is probably a rate limit from GitHub. Breach itself does not so that many request (2 at startup)

**Comment by HLFH** [comment]
Ok. Solved. I updated to Mavericks, installed Command Line Tools, rebooted, ... It works now. Thanks.

**Comment by spolu** [comment]
Awesome!

-stan

—
Stanislas Polu
Ph: +1 415 216 5700 | Tw: @spolu
_TOTEMS_ | Instagram Marketing Suite | http://totems.co
