### ISSUE TITLE
Closing tabs other than the first one

### ISSUE THREAD

**Issue by hardfire** [breach/mod_strip#36]
When i try to close the tab other than the first one, the tab comes into active mode, but doesnt close.

**Comment by spolu** [comment]
Yep I see why there was a fix made to select tabs under search which installed a mouse down event which gets called before the click event goes to the delete button. 

We just need to use mouse down on the delete button to fix this

**Comment by spolu** [comment]
Tagged as bug

**Comment by hardfire** [comment]
aha! right! didin't think of that .. sending in a PR!

**Comment by spolu** [comment]
Awesome thanks!
