### ISSUE TITLE
Management of content frame

### ISSUE THREAD

**Issue by Pectojin** [breach/mod_strip#45]
I was wanting to do some work on mod_strip, which involved catching keypresses happening on the actual content frame, and then do an action with data from the content frame. However since it's in iframes this doesn't seem possible, does the core provide any access to other iframes or should these kinds of things be put in the core?
An example is CTRL+S saving the page, which i think is a functionality that all browsers must have.

**Comment by spolu** [comment]
in mod_strip. `lib/*` including `lib/keyboard_shorcuts.js` are executed in a NodeJS context (not the web frame) and have access to the `breach_core` API to receive keyboard events.

So you can totally do that using the same API.
I would suggest though creating your own module and add it to the list of modules here: 

https://github.com/breach/breach_core/wiki/List-of-modules

**Comment by Pectojin** [comment]
Sweet. I'll see if I come up with anything cool.
Also, I totally missed that list. I thought breach only had strip and stats. Awesome to see so many modules in development.

**Comment by spolu** [comment]
Awesome!
