### ISSUE TITLE
Shortcuts doesn't work

### ISSUE THREAD

**Issue by MrShemek** [breach/mod_strip#52]
I've got file called keyboard_shortcuts.js under ~/.breach/modules/breach/mod_strip#v0.2.11-alpha.5/lib/keyboard_shortcuts.js but when i press for example CTRL+T nothing happens. Any idea how to fix it?

**Comment by spolu** [comment]
Can you input stuff on any web page?

**Comment by MrShemek** [comment]
Sure, now I'm writing using Breach :)
I've got problems with sandbox so i copied it from chrome, change owner and chmods and it works. Before that I was using solution with flag for file from exo_browser and there shortcuts didn't work.

And one more information - I reinstalled mod_strip and it didn't help.

**Comment by spolu** [comment]
You can use the chrome sandbox directly using this:

```
CHROME_DEVEL_SANDBOX=/opt/google/chrome/chrome-sandbox
```

If you have chrome installed...

Have you tried restarting mod_strip?

**Comment by MrShemek** [comment]
I've removed chrome-sandbox from mantioned before folder, use commend from you and now I have error:

> Running without the SUID sandbox!

**Comment by spolu** [comment]
You have to have this in your env or prefix the execution with that variable

**Comment by MrShemek** [comment]
Wow, how can i be so stupid? Now Breach works but shortcuts still don't.

**Comment by spolu** [comment]
Very surprising... shortcut support is directly handled by the content API. Will mark as bug

**Comment by MrShemek** [comment]
Thanks a lot, i'm waiting for stable version :)

**Comment by kyleshrader** [comment]
Num Lock (and or ALTGR) is the issue. Turn off numlock for the time being.
https://github.com/breach/mod_strip/pull/33 will fix this. :)

**Comment by MrShemek** [comment]
@kylekinkade you're right! Thanks a lot, I owe you a beer :)
