### ISSUE TITLE
Search bar wipes search term on focus lost

### ISSUE THREAD

**Issue by JamoBox** [breach/mod_strip#53]
There is a minor bug when typing a search in the URL bar, if the window loses focus the search term is wiped and set back to an empty box if on a blank page, or if on a page the page's URL.
The search term should persist until the user either cancels it by clicking elsewhere on the page or hitting escape. This is mainly down to intuitiveness, so perhaps it's not so much as a bug but a feature request.

**Comment by spolu** [comment]
Thanks! Marked as bug. PRs welcome! :)

**Comment by jonathan-reisdorf** [comment]
see this PR: https://github.com/breach/mod_strip/pull/66

behavior is now more like in other browsers, also clicking on the document will not erase search term unless it was empty. but I have one more question: should it be erased on tab change? if so, what could be the best practise to achieve that? box and strip are different components and just getting the status change is not information enough to detect that the user has clicked on a different tab afaik
